**The Basics**


In [ ]:
import numpy as np


In [ ]:
a= np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [ ]:
b= np.array([[1,2,3,4,10],[6,7,8,9,24]])
b

array([[ 1,  2,  3,  4, 10],
       [ 6,  7,  8,  9, 24]])

In [ ]:
# get dimension
a.ndim
b.ndim
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#get shape
a.shape

(4,)

In [ ]:
# get type
a.dtype

dtype('int64')

In [ ]:
# get size
a.size


4

In [ ]:
# get bytes
a.nbytes

32

**Accessing / changing specific element ,row , column**


In [ ]:
import numpy as np

In [ ]:
a= np.array([[12,1,3,45,6,7,7],[9,56,8,3,8,1,2]])
a

array([[12,  1,  3, 45,  6,  7,  7],
       [ 9, 56,  8,  3,  8,  1,  2]])

In [ ]:
# get specific element
a[1,1]

56

In [ ]:
# get specific row
a[1,:]

array([ 9, 56,  8,  3,  8,  1,  2])

In [ ]:
# get specific column
a[:,6]

array([7, 2])

In [ ]:
# getting little more complex [startindex:endindex:stepsize]
a[1,0:7:3]

array([9, 3, 2])

In [ ]:
# changing and replace the element
a[0,3]=24
a

array([[12,  1,  3, 24,  6,  7,  7],
       [ 9, 56,  8,  3,  8,  1,  2]])

In [ ]:
a[:,6]=10,24
a

array([[12,  1,  3, 24,  6,  7, 10],
       [ 9, 56,  8,  3,  8,  1, 24]])

*3-d Example

In [ ]:
b= np.array([[[2,4],[3,5]],[[10,36],[27,29]]])
b

array([[[ 2,  4],
        [ 3,  5]],

       [[10, 36],
        [27, 29]]])

In [ ]:
# getting specific element
b[1,0,0]

10

In [ ]:
# replace
b[:,:,1]=[[1,2],[4,0]]
b

array([[[ 2,  1],
        [ 3,  2]],

       [[10,  4],
        [27,  0]]])

**Initilizing different types of arrays**

In [ ]:
# all zeros matrix
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# all ones matrix and i can pass data type as well
np.ones((3,3) ,dtype ='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
# any other number
np.full((3,3),15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [ ]:
# any other number (full_like)
np.full_like(b,3)

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [ ]:
# random decimal matrix
np.random.rand(3,2)

array([[0.37366027, 0.50747407],
       [0.50128791, 0.2374176 ],
       [0.89223445, 0.9290265 ]])

In [ ]:
# randm integer matrix (range from to and size)
np.random.randint(1,7, size=(3,4))

array([[6, 3, 2, 3],
       [3, 3, 4, 2],
       [4, 1, 3, 3]])

In [ ]:
# identitey matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# repeat an array
array = np.array([[1,2,3,4]])
r = np.repeat(array,3, axis =0)
r

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# creat 5*5 array in which all first row first column and last row last column has all 0 values and middle element is 9 and rest is 1
main = np.zeros((5,5))
main

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
c =np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c[1,1]=9
c

array([[1., 1., 1.],
       [1., 9., 1.],
       [1., 1., 1.]])

In [ ]:
main[1:-1,1:-1] = c
main

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 9., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# copy array using copy function
d = np.array([9,8,7])
e = d.copy()
e

array([9, 8, 7])

In [ ]:
e[1] = 43

In [ ]:
e

array([ 9, 43,  7])

In [ ]:
d

array([9, 8, 7])

**Mathematics**

In [ ]:
x = np.array([11,12,13,14,15])
x

array([11, 12, 13, 14, 15])

In [ ]:
# arthematic operation with array
x+=2
x

array([13, 14, 15, 16, 17])

In [ ]:
x-=11
x

array([0, 1, 2, 3, 4])

In [ ]:
x*=2
x

array([22, 24, 26, 28, 30])

In [ ]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b= np.array([7,56,8,8])
b

array([ 7, 56,  8,  8])

In [ ]:
# adding two matrix
a  + b

array([ 8, 58, 11, 12])

In [ ]:
# multiplication of matrix
a*b

array([  7, 112,  24,  32])

In [ ]:
A = np.array([[2,3,4,],[5,6,8],[8,9,10]])
A

array([[ 2,  3,  4],
       [ 5,  6,  8],
       [ 8,  9, 10]])

In [ ]:
B =np.array([[2,6,4,],[5,6,18],[8,3,10]])
B

array([[ 2,  6,  4],
       [ 5,  6, 18],
       [ 8,  3, 10]])

In [ ]:
# multiplication of 3*3 matrix
A*B

array([[  4,  18,  16],
       [ 25,  36, 144],
       [ 64,  27, 100]])

In [ ]:
# Trignometric values
np.sin(A)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.98935825],
       [ 0.98935825,  0.41211849, -0.54402111]])

In [ ]:
np.cos(A)

array([[-0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029, -0.14550003],
       [-0.14550003, -0.91113026, -0.83907153]])

In [ ]:
# you can find all the function of Trignometric

**Linear Algebra**

In [ ]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b=np.full((3,2) ,2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [ ]:
# finding determinant
x= np.identity((3))
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linalg.det(x)

1.0

**Statistics**

In [ ]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(array)

1

In [ ]:
np.max(array)

6

In [ ]:
np.max(array , axis = 0)

array([4, 5, 6])

In [ ]:
np.sum(array)

21

In [ ]:
np.sum(array , axis=0)

array([5, 7, 9])

**Reorganizing arrays**

In [ ]:
# reshape the array
before = np.array([[7,5,5,5],[2,3,5,7]])
before

array([[7, 5, 5, 5],
       [2, 3, 5, 7]])

In [ ]:
after = before.reshape((4,2))
after

array([[7, 5],
       [5, 5],
       [2, 3],
       [5, 7]])

In [ ]:
# stacking vectors
v1 = np.array([2,6,9])
v2 = np.array([6,8,2])

In [ ]:
# verticallay stacking vector
np.vstack([v1,v2])

array([[2, 6, 9],
       [6, 8, 2]])

In [ ]:
np.vstack([v1,v2,v2,v1])

array([[2, 6, 9],
       [6, 8, 2],
       [6, 8, 2],
       [2, 6, 9]])

In [ ]:
# horizontal stacking vector
np.hstack([v2,v1])

array([6, 8, 2, 2, 6, 9])

**Eigen values and Eigen Vectors**

In [ ]:
matrix = np.array([[10,11,12],[14,15,16],[17,18,19]])


In [ ]:
matrix

array([[10, 11, 12],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
print("Eigen values are :" ,np.linalg.eigvals(matrix))


Eigen values are : [ 4.44722051e+01 -4.72205054e-01  6.71776095e-16]
